apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot.name" . }}-secrets
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
